# Generated by Django 5.0.2 on 2024-02-16 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0003_alter_attendance_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='generated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
