# Generated by Django 5.0.2 on 2024-02-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0006_alter_payslip_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(null=True),
        ),
    ]
