# Generated by Django 5.0.2 on 2024-02-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0007_alter_attendance_time_in_alter_attendance_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='remark',
            field=models.CharField(choices=[('FULL', 'Full Day'), ('HALF', 'Half Day'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HOLIDAY', 'Holiday'), ('LEAVE', 'Leave')], max_length=7),
        ),
    ]
