# Generated by Django 5.0.2 on 2024-02-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0008_alter_attendance_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='minutes_late',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
