# Generated by Django 5.0.2 on 2024-04-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0011_remove_payslip_absent_attendance_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='cooperative_deduction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='member_status',
            field=models.IntegerField(default=0),
        ),
    ]
