# Generated by Django 5.0.2 on 2024-04-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payroll', '0012_payslip_cooperative_deduction_payslip_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='undertime_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='undertime_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
