# Generated by Django 5.0.2 on 2024-04-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cooperative_member',
            field=models.BooleanField(default=False),
        ),
    ]
